### ISSUE TITLE
 Discussion: Examples for mowing automations with this integration

### ISSUE THREAD

**Issue by northpower25** [py-smart-gardena/hass-gardena-smart-system#32]
I think it helps all (specialy new users) if we collect and discuss automations (here for mowing control) and rerequisits for those. For irrigation we discuss this here -> #30

**Comment by northpower25** [comment]
**Target:**
Notification over [HomeAssistant Companion App](https://companion.home-assistant.io/) or as [Telegram Messenger](https://www.home-assistant.io/integrations/telegram/) message or over [Amazon Alexa with the help of Alexa Media Player Integration](https://github.com/custom-components/alexa_media_player)

**Why not with the Gardena App:**
It is not possible to get Messages from the status of the [Gardena Mowers](https://www.gardena.com/de/produkte/rasenpflege/mahroboter/).

It is not possible to get this notifications over Amazon Alexa from the App

** Requirements **

1. Installed hass-gardena-smart-system integration
2. [Home Assistant Compagnion iOS or Android App](https://companion.home-assistant.io/)
3. [Gardena Mower](https://www.gardena.com/de/produkte/rasenpflege/mahroboter/)
4. (optional) [Telegram Messenger Integration](https://www.home-assistant.io/integrations/telegram/)
5. (optional) [Alexa Media Player Integration](https://github.com/custom-components/alexa_media_player) you can find and install this Integration over HACS 

**Configuration:**
to get the activity Statuscode as sensor for the automation trigger you need the activity attribut as seperat template sensor in the configuration.yaml
```sensor:
  - platform: template
    sensors:
      sileno_activity:
        value_template: "{{ states.vacuum.sileno.attributes.activity }}"
        friendly_name: "Sileno Aktivität"
```

**Automation example:**

```
- alias: "Docked with Autotimer"
  trigger:
    platform: state
    entity_id: sensor.sileno_activity
    to: 'PARKED_AUTOTIMER'
  action:
    - service: notify.notify
      data:
        title: "Mower docked"
        message: "Lawn mower was parked due to autotimer"
    - service: notify.telegram_[TELEGRAM_CHANNEL]
      data_template:
        title: '*Mower docked!*'
        message: "Lawn mower was parked due to autotimer -> https://[HA_URL]/lovelace/terrasse"

- alias: "Lawnmower mows"
  trigger:
    platform: state
    entity_id: sensor.sileno_activity
    to: 'OK_CUTTING'
  action:
    - service: notify.notify
      data:
        title: "Mower Status"
        message: "Lawnmower mows"
    - service: notify.telegram_[TELEGRAM_CHANNEL]
      data_template:
        title: '*Mower Status*'
        message: "Lawnmower mows -> https://[HA_URL]/lovelace/terrasse"

- alias: "Lawnmower loads"
  trigger:
    platform: state
    entity_id: sensor.sileno_activity
    to: 'OK_CHARGING'
  action:
    - service: notify.notify
      data:
        title: "Mower Status"
        message: "Lawnmower loads"
    - service: notify.telegram_[TELEGRAM_CHANNEL]
      data_template:
        title: '*Lawnmower loads*'
        message: "Lawnmower loads -> https://[HA_URL]/lovelace/terrasse"

- alias: "Mower Error"
  trigger:
    - platform: state
      entity_id: vacuum.sileno
      to: 'error'
  action:
    - service: notify.notify
      data:
        title: "Mower Fehler"
        message: "Error: {{ states.sensor.sileno_error_status.state }}!"
    - service: notify.telegram_[TELEGRAM_CHANNEL]
      data_template:
        title: '*Mower Error*'
        message: "Error: {{ states.sensor.sileno_error_status.state }}! -> https://[HA_URL]/lovelace/terrasse"

```
