### ISSUE TITLE
Error state but need more detail

### ISSUE THREAD

**Issue by jeremycoppey** [py-smart-gardena/hass-gardena-smart-system#74]
![image](https://user-images.githubusercontent.com/13691266/122050885-3d52b480-cde4-11eb-8d66-ec2426613b8d.png)
He reached the daily limit of operation (overheating i'm presuming) 
![image](https://user-images.githubusercontent.com/13691266/122050678-fb297300-cde3-11eb-94f1-176acf99cd7f.png)
How do I show those extra error state?

**Comment by grm** [comment]
Hello,

in order to do that, you need to create a sensor from the attribute.
This can be done by creating a new sensor like this : 
```
template:
  - sensor:
    - name: 'Sileno Error'
      state: "{{ state_attr('vacuum.sileno', 'error') }}"
```

and then you can use **sensor.sileno_error** from your template.
